name: Build Electron Artifacts

on:
  workflow_dispatch:

jobs:
  macos-arm64:
    runs-on: macos-14
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: false
      ELECTRON_BUILDER_DISABLE_NATIVE_DEPENDENCY_CHECK: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Build DMG (arm64)
        run: npm run dist:mac:arm64
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-artifacts
          path: dist/**

  windows:
    runs-on: windows-latest
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: false
      ELECTRON_BUILDER_DISABLE_NATIVE_DEPENDENCY_CHECK: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Build EXE (NSIS)
        run: npm run dist:win
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: dist/**


